# Generated by Django 5.0.6 on 2024-05-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoAtuntaqui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='generarpagoatuntaqui',
            table='genera_pago_atuntaqui',
        ),
    ]
