# Generated by Django 5.0.6 on 2024-06-05 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoAtuntaqui', '0002_alter_generarpagoatuntaqui_table'),
        ('ventasAtuntaqui', '0002_alter_ventasatuntaqui_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagoatuntaqui',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagoatuntaqui',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasAtuntaqui.ventasatuntaqui'),
        ),
    ]
