# Generated by Django 5.0.6 on 2024-06-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoAtuntaqui', '0004_generarpagoatuntaqui_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagoatuntaqui',
            name='venta',
        ),
    ]
