# Generated by Django 5.0.6 on 2024-05-17 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad_ingresar', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('talla', models.CharField(max_length=30)),
                ('fecha_ingresa_producto', models.DateField()),
                ('modelo', models.CharField(max_length=30)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.factura')),
            ],
        ),
    ]
