# Generated by Django 5.0.6 on 2024-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
