# Generated by Django 5.0.6 on 2024-06-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoOtavalo', '0001_initial'),
        ('ventasOtavalo', '0002_alter_ventasotavalo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagootavalo',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagootavalo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasOtavalo.ventasotavalo'),
        ),
    ]
