# Generated by Django 5.0.6 on 2024-06-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoAngel', '0003_alter_generarpagoangel_idcliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generarpagoangel',
            old_name='idCliente',
            new_name='venta',
        ),
    ]
