# Generated by Django 5.0.6 on 2024-06-25 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0008_remove_clientesangel_estado_and_more'),
        ('generarPagoAngel', '0004_rename_idcliente_generarpagoangel_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagoangel',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesAngel.clientesangel'),
        ),
    ]
