# Generated by Django 5.0.6 on 2024-06-25 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoAngel', '0005_generarpagoangel_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagoangel',
            name='venta',
        ),
    ]
