# Generated by Django 5.0.6 on 2024-06-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devolucionesHistorial', '0002_devolucioneshistorial_proveedor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devolucioneshistorial',
            table='devoluciones_historial',
        ),
    ]
