# Generated by Django 5.0.6 on 2024-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockHistoria', '0002_alter_stockhistoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistoria',
            name='fecha',
            field=models.DateField(),
        ),
    ]
