# Generated by Django 5.0.6 on 2024-06-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockHistoria', '0004_stockhistoria_precio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockhistoria',
            table='stock_historial',
        ),
    ]
