# Generated by Django 5.0.6 on 2024-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentasHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('cantidad_venta', models.IntegerField()),
                ('fecha', models.DateField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
