# Generated by Django 5.0.6 on 2024-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasHistorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventashistorial',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=50),
            preserve_default=False,
        ),
    ]
