# Generated by Django 5.0.6 on 2024-06-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasMira', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventasmira',
            table='ventas_mira',
        ),
    ]
