# Generated by Django 5.0.6 on 2024-06-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasMira', '0002_alter_ventasmira_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasmira',
            name='cantidad_adeudada',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=50),
            preserve_default=False,
        ),
    ]
