# Generated by Django 5.0.6 on 2024-06-05 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoBolivar', '0001_initial'),
        ('ventasBolivar', '0002_alter_ventasbolivar_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagobolivar',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagobolivar',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasBolivar.ventasbolivar'),
        ),
    ]
