# Generated by Django 5.0.6 on 2024-06-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesBolivar', '0002_remove_clientesbolivar_cantidad_producto_and_more'),
        ('generarPagoBolivar', '0002_remove_generarpagobolivar_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagobolivar',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesBolivar.clientesbolivar'),
        ),
    ]
