# Generated by Django 5.0.6 on 2024-06-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasCayambe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventascayambe',
            table='ventas_cayambe',
        ),
    ]
