# Generated by Django 5.0.6 on 2024-06-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasAtuntaqui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventasatuntaqui',
            table='ventas_atuntaqui',
        ),
    ]
