# Generated by Django 5.0.6 on 2024-06-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesLagoagrio', '0002_remove_clienteslagoagrio_cantidad_producto_and_more'),
        ('generarPagoLagoagrio', '0002_remove_generarpagolagoagrio_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagolagoagrio',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesLagoagrio.clienteslagoagrio'),
        ),
    ]
