# Generated by Django 5.0.6 on 2024-06-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoLagoagrio', '0003_generarpagolagoagrio_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagolagoagrio',
            name='venta',
        ),
    ]
