# Generated by Django 5.0.6 on 2024-06-05 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoCayambe', '0001_initial'),
        ('ventasCayambe', '0002_alter_ventascayambe_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagocayambe',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagocayambe',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasCayambe.ventascayambe'),
        ),
        migrations.AlterModelTable(
            name='generarpagocayambe',
            table='genera_pago_cayambe',
        ),
    ]
