# Generated by Django 5.0.6 on 2024-06-25 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesCayambe', '0002_remove_clientescayambe_cantidad_producto_and_more'),
        ('generarPagoCayambe', '0002_remove_generarpagocayambe_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagocayambe',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesCayambe.clientescayambe'),
        ),
    ]
