# Generated by Django 5.0.6 on 2024-06-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoCayambe', '0003_generarpagocayambe_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagocayambe',
            name='venta',
        ),
    ]
