# Generated by Django 5.0.6 on 2024-05-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientesAngel', '0008_remove_clientesangel_estado_and_more'),
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoClienteAngel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fecha_venta', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientesAngel.clientesangel')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
            options={
                'db_table': 'producto_cliente',
            },
        ),
    ]
