# Generated by Django 5.0.6 on 2024-05-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0008_remove_clientesangel_estado_and_more'),
        ('inventario', '0002_alter_inventario_table'),
        ('productoClienteAngel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoclienteangel',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesAngel.clientesangel'),
        ),
        migrations.AlterField(
            model_name='productoclienteangel',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario'),
        ),
    ]
