# Generated by Django 5.0.6 on 2024-06-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoClienteAngel', '0002_alter_productoclienteangel_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoclienteangel',
            table='ventas_angel',
        ),
    ]
