# Generated by Django 5.0.6 on 2024-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoClienteAngel', '0003_alter_productoclienteangel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoclienteangel',
            name='cantidad_adeudada',
            field=models.DecimalField(decimal_places=2, default=1233, max_digits=50),
            preserve_default=False,
        ),
    ]
