# Generated by Django 5.0.6 on 2024-06-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesOtavalo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesotavalo',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='clientesotavalo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clientesotavalo',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='clientesotavalo',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='clientesotavalo',
            name='total_pagar',
        ),
    ]
