# Generated by Django 5.0.6 on 2024-05-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientesangel',
            table='clientes_angel',
        ),
    ]
