# Generated by Django 5.0.6 on 2024-05-21 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0002_alter_clientesangel_table'),
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesangel',
            name='producto',
        ),
        migrations.AddField(
            model_name='clientesangel',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario'),
        ),
    ]
