# Generated by Django 5.0.6 on 2024-05-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0003_remove_clientesangel_producto_clientesangel_producto'),
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesangel',
            name='producto',
        ),
        migrations.AddField(
            model_name='clientesangel',
            name='producto',
            field=models.ManyToManyField(to='inventario.inventario'),
        ),
    ]
