# Generated by Django 5.0.6 on 2024-05-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0004_remove_clientesangel_producto_clientesangel_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesangel',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='clientesangel',
            name='producto',
        ),
    ]
