# Generated by Django 5.0.6 on 2024-05-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0005_remove_clientesangel_cantidad_producto_and_more'),
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesangel',
            name='productos',
            field=models.ManyToManyField(to='inventario.inventario'),
        ),
        migrations.CreateModel(
            name='ProductoClienteAngel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientesAngel.clientesangel')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
            options={
                'db_table': 'producto_cliente',
            },
        ),
    ]
