# Generated by Django 5.0.6 on 2024-05-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAngel', '0007_remove_clientesangel_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesangel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clientesangel',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='clientesangel',
            name='total_pagar',
        ),
    ]
