# Generated by Django 5.0.6 on 2024-06-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasBolivar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ventasbolivar',
            table='ventas_bolivar',
        ),
    ]
