# Generated by Django 5.0.6 on 2024-06-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoMira', '0001_initial'),
        ('ventasMira', '0002_alter_ventasmira_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagomira',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagomira',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasMira.ventasmira'),
        ),
    ]
