# Generated by Django 5.0.6 on 2024-06-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesMira', '0002_remove_clientesmira_cantidad_producto_and_more'),
        ('generarPagoMira', '0002_remove_generarpagomira_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagomira',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesMira.clientesmira'),
        ),
    ]
