# Generated by Django 5.0.6 on 2024-05-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
        ('inventario', '0002_alter_inventario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoluciones',
            name='codigo',
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='devolucion',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devoluciones',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario'),
        ),
    ]
