# Generated by Django 5.0.6 on 2024-05-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0002_remove_devoluciones_codigo_devoluciones_devolucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoluciones',
            name='descripcion',
        ),
    ]
