# Generated by Django 5.0.6 on 2024-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0003_remove_devoluciones_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devoluciones',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='devoluciones',
            name='talla',
        ),
    ]
