# Generated by Django 5.0.6 on 2024-06-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoPimampiro', '0001_initial'),
        ('ventasPimampiro', '0002_alter_ventaspimampiro_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagopimampiro',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagopimampiro',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasPimampiro.ventaspimampiro'),
        ),
    ]
