# Generated by Django 5.0.6 on 2024-06-25 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesPimampiro', '0002_remove_clientespimampiro_cantidad_producto_and_more'),
        ('generarPagoPimampiro', '0002_remove_generarpagopimampiro_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagopimampiro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesPimampiro.clientespimampiro'),
        ),
    ]
