# Generated by Django 5.0.6 on 2024-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoPimampiro', '0003_generarpagopimampiro_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagopimampiro',
            name='venta',
        ),
    ]
