# Generated by Django 5.0.6 on 2024-06-05 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generarPagoIbarra', '0001_initial'),
        ('ventasIbarra', '0002_alter_ventasibarra_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generarpagoibarra',
            name='idCliente',
        ),
        migrations.AddField(
            model_name='generarpagoibarra',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventasIbarra.ventasibarra'),
        ),
        migrations.AlterModelTable(
            name='generarpagoibarra',
            table='genera_pago_ibarra',
        ),
    ]
