# Generated by Django 5.0.6 on 2024-06-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesIbarra', '0002_remove_clientesibarra_cantidad_producto_and_more'),
        ('generarPagoIbarra', '0002_remove_generarpagoibarra_idcliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generarpagoibarra',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientesIbarra.clientesibarra'),
        ),
    ]
